### ISSUE TITLE
事务切面中对乐观锁与socket超时异常不做回滚处理，只抛异常？

### ISSUE THREAD

**Issue by RumiaLunnar** [Zh1Cheung/tyloo#2]
CompensableTransactionInterceptor类中

        try {

            // 事务开始（创建事务日志记录，并在当前线程缓存该事务日志记录）
            transaction = transactionManager.begin(compensableMethodContext.getUniqueIdentity());

            try {
                // Try (开始执行被拦截的方法)
                returnValue = compensableMethodContext.proceed();
            } catch (Throwable tryingException) {

                if (!isDelayCancelException(tryingException, allDelayCancelExceptions)) {

                    logger.warn(String.format("compensable transaction trying failed. transaction content:%s", JSON.toJSONString(transaction)), tryingException);

                    transactionManager.rollback(asyncCancel);
                }

                throw tryingException;
            }

**Comment by Zh1Cheung** [comment]
不立即回滚，主要考虑是被调用方存在一直在正常执行的可能，只是执行的慢，导致了调用方超时。此时如果立即回滚，在被调用方执行cancel操作的同时，被调用方的try方法还在执行，甚至cancel操作执行完了，try方法还没结束，这种情况下业务数据存在不一致的可能。

目前解决办法是这类异常不立即回滚，而是由恢复job执行回滚，恢复job会在一段时间后再去调用该被调用方的cancel方法，这个时间可在RecoverConfig中设置，默认120s。

**Comment by RumiaLunnar** [comment]
🐂🍺
